# Site settings
title:       Vikram Meyer
email:       vjmeyer20@gmail.com
author:      Vikram Meyer
description: "Hi! I'm Vikram."
baseurl:     ""
url:         "http://meyerv11045.github.io"
date_format: "%B %-d, %Y"

# code highlighting

# Google services
google_verification:
google_analytics:
google_tag_manager:
bing_verification:

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Facebook Page integration
fb_page: false
fb_page_id:

# Disqus post comments
disqus_shortname:

# Facebook Comments plugin
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: meyerv11045
bitbucket_username:
stackoverflow_id:
twitter_username:
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: vikram-meyer
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username:
vk_id:
google_scholar:

# Post sharing icons
show_sharing_icons: false
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         ''
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'your e-mail'
    content:  ''
    subject:  'hello'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown: kramdown
kramdown:
    math_engine: nil
    input: GFM
    highlighter: rouge
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude: [vendor, notebooks, Gemfile, Gemfile.lock, Rakefile, deploy.sh, scraps, latex, LICENSE.txt]
